variable "aws_profile" {}
variable "region" {}
variable "ProjectName" {}
variable "cidrBlock" {}
variable "containerImage" {}
variable "containerImageBackend" {}
variable "InstanceType" {}
variable "KeyName" {}
variable "github_token" {}
variable "aws_region" {}
variable "account_id" {}