variable "ProjectName" {}
variable "containerImage" {}
variable "containerImageBackend" {}
variable "PublicSubnetIDs" {}
variable "fargateTargetGroupARN" {}
variable "fargateTargetGroupBackendARN" {}
variable "ecsFargateSecurityGroupFrontendID" {}
variable "ecsFargateSecurityGroupBackendID" {}
variable "backendDomain" {}